# Generated by Django 3.1.2 on 2020-11-03 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuenta', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='calle',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='perfil',
            name='comuna',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='perfil',
            name='departamento',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='perfil',
            name='region',
            field=models.CharField(default='', max_length=50),
        ),
    ]
