# Generated by Django 3.1.2 on 2020-11-03 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cuenta', '0002_auto_20201103_1803'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='direccion',
        ),
        migrations.DeleteModel(
            name='Direccion',
        ),
    ]
