# Generated by Django 3.1.2 on 2020-11-02 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreLente', models.CharField(max_length=50)),
                ('codLente', models.CharField(max_length=50)),
                ('precioLente', models.CharField(max_length=50)),
                ('imagenLente', models.ImageField(upload_to='img')),
            ],
        ),
    ]
