# Generated by Django 3.1.2 on 2020-11-03 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0002_auto_20201102_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='precioLente',
            field=models.CharField(max_length=50),
        ),
    ]
